FROM ubuntu:24.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       curl ca-certificates util-linux \
    && curl -L https://github.com/zellij-org/zellij/releases/download/v0.43.1/zellij-x86_64-unknown-linux-musl.tar.gz \
       | tar xz -C /usr/local/bin \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /test
